<?php
namespace App\Http\Controllers\Api;
use App\Actions\Orders\CompleteOrder; use App\Actions\Orders\VoidOrder; use App\Enums\OrderStatus; use App\Http\Requests\Api\StoreOrderRequest; use App\Http\Requests\Api\VoidOrderRequest; use App\Http\Resources\OrderResource; use App\Models\Order; use App\Models\User; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Validation\Rule; use Illuminate\Validation\ValidationException;
/** @group Orders */ class OrderController extends ApiController {
public function store(StoreOrderRequest $r,CompleteOrder $a):JsonResponse{$o=$a->handle($r->user(),$r->validated());return $this->success(new OrderResource($o),'Order diproses.',201);}
public function index(Request $r):JsonResponse{$v=$r->validate(['status'=>['nullable',Rule::enum(OrderStatus::class)],'shift_id'=>['nullable','integer'],'per_page'=>['nullable','integer','between:1,100']]);$q=Order::with(['items.modifiers','payment'])->where('cashier_id',$r->user()->id)->latest();$q->when($v['status']??null,fn($q,$x)=>$q->where('status',$x));$q->when($v['shift_id']??null,fn($q,$x)=>$q->where('shift_id',$x));$p=$q->paginate($v['per_page']??15);return $this->success(['items'=>OrderResource::collection($p->items()),'pagination'=>['current_page'=>$p->currentPage(),'last_page'=>$p->lastPage(),'per_page'=>$p->perPage(),'total'=>$p->total()]]);}
public function show(Request $r,Order $order):JsonResponse{$this->own($r,$order);return $this->success(new OrderResource($order->load(['items.modifiers','payment'])));}
public function hold(Request $r,Order $order):JsonResponse{$this->own($r,$order);if($order->status!==OrderStatus::DRAFT)throw ValidationException::withMessages(['order'=>'Hanya draft dapat di-hold.']);$order->update(['status'=>OrderStatus::HELD]);return $this->success(new OrderResource($order->fresh()),'Order ditahan.');}
public function complete(Request $r,Order $order):JsonResponse{$this->own($r,$order);$r->validate(['submission_token'=>['required','uuid']]);if($order->submission_token!==$r->input('submission_token'))throw ValidationException::withMessages(['submission_token'=>'Token tidak cocok.']);if($order->status!==OrderStatus::COMPLETED)throw ValidationException::withMessages(['order'=>'Order belum melalui atomic checkout.']);return $this->success(new OrderResource($order->load(['items.modifiers','payment'])),'Order sudah selesai.');}
public function void(VoidOrderRequest $r,Order $order,VoidOrder $a):JsonResponse{$this->own($r,$order);$m=User::findOrFail($r->integer('approved_by'));return $this->success(new OrderResource($a->handle($order,$r->user(),$m,$r->string('pin'),$r->string('reason'),$r->boolean('restock',true))),'Order dibatalkan.');}
private function own(Request $r,Order $o):void{abort_unless($o->cashier_id===$r->user()->id||$r->user()->hasRole('OWNER','MANAGER'),403);}}
